# -*- coding: utf-8 -*-
"""datacleaning_salary.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I2zP1P0Rt_ThnIZ7aHZOMfDXjs602xsS
"""

import pandas as pd

salary = pd.read_csv("salary_dataset.csv")
salary.info()

salary

"""1. Change data type
(done)

2. Drop Duplicate
"""

salary=salary.drop_duplicates()

salary.info()

salary

607 - 562

45/607

"""3. Handle Missing Data

4. Remove Outliers
"""

#Before
salary.boxplot(column='salary_in_usd')

salary['salary_in_usd'].describe()

q1 = salary['salary_in_usd'].quantile(0.25)
q3 = salary['salary_in_usd'].quantile(0.75)
upper_limit = q3 +  1.5 * (q3-q1)
lower_limit = q1 -  1.5 * (q3-q1)

salary = salary[salary['salary_in_usd'] > lower_limit]
salary = salary[salary['salary_in_usd'] < upper_limit]
salary['salary_in_usd'].describe()

#After
salary.boxplot(column='salary_in_usd')

salary.info()

562-552

10/562

salary

salary.to_csv('salary-dataset.csv')

from google.colab import files
files.download('salary-dataset.csv')